<a href="https://colab.research.google.com/github/ariwells2001/mlfromscratch/blob/main/logic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def numerical_derivative(f,x):
  delta_x = 1e-4
  grad = np.zeros_like(x) 
 # print("debug1. initial input vairable = {}".format(x))
  #print("debug2. initial grad = {}".format(grad))
  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished:
    idx = it.multi_index
    
  #  print("debug3. idx = {},x[idx] ={}".format(idx,x[idx]))

    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)
    x[idx] = float(tmp_val) - delta_x
    fx2= f(x)
    grad[idx] = (fx1-fx2)/(2*delta_x)
    
 #   print("debug 4. grad[idx = {}".format(grad[idx]))
  #  print("debug 5. grad= {}".format(grad))
 #   print("==================================================")
  
    x[idx] = tmp_val
    it.iternext()

  return grad

In [1]:
import numpy as np

def sigmoid(x):
  return 1/(1+np.exp(-x))


In [10]:
class LogicGate:
  def __init__(self,gate_name,xdata,tdata):
    self.name = gate_name
    
    self.__xdata = xdata.reshape(4,2)
    self.__tdata = tdata.reshape(4,1)

    self.__W = np.random.rand(2,1)
    self.__b = np.random.rand(1)

    self.__learning_rate = 1e-2

  def __loss_func(self):

    delta = 1e-7
    z = np.dot(self.__xdata,self.__W) + self.__b
    y = sigmoid(z)

    return  -np.sum(self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1-y)+delta))

  def error_val(self):
    delta = 1e-7
    z = np.dot(self.__xdata,self.__W) + self.__b
    y = sigmoid(z)

    return  -np.sum(self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1-y)+delta)) 

  def train(self):
    f = lambda x: self.__loss_func()
    print("Initial error value = ", self.error_val())
    for step in range(8001):
      
      self.__W -= self.__learning_rate * numerical_derivative(f,self.__W)
      self.__b -= self.__learning_rate * numerical_derivative(f,self.__b)

      if(step % 400 == 0):
        print("step = ", step, "error value = ", self.error_val())

  def predict(self,input_data):
    
    z = np.dot(input_data, self.__W) + self.__b
    y = sigmoid(z)

    if y > 0.5:
      result = 1
    else:
      result = 0
    
    return y, result



In [11]:
xdata = np.array([0,0,0,1,1,0,1,1])
tdata = np.array([0,0,0,1])
test = xdata.reshape(4,2)
print(test)
AND_obj = LogicGate("AND_GATE",xdata,tdata)

AND_obj.train()


[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Initial error value =  3.8945439056191433
step =  0 error value =  3.852443916699871
step =  400 error value =  1.5685012863835528
step =  800 error value =  1.1582798599813537
step =  1200 error value =  0.9283934726715339
step =  1600 error value =  0.7776085009277356
step =  2000 error value =  0.6696293752156107
step =  2400 error value =  0.5879566646244315
step =  2800 error value =  0.5238252759520731
step =  3200 error value =  0.47206481246972143
step =  3600 error value =  0.4293924595314156
step =  4000 error value =  0.3936081483913266
step =  4400 error value =  0.36317530138909593
step =  4800 error value =  0.3369851522433589
step =  5200 error value =  0.3142161375501946
step =  5600 error value =  0.2942459239182791
step =  6000 error value =  0.2765941912898033
step =  6400 error value =  0.2608842017380085
step =  6800 error value =  0.24681627412673024
step =  7200 error value =  0.2341490442175736
step =  7600 error value =  0.222685954

In [13]:
print(AND_obj.name,"\n")

test_data = np.array([[0,0],[0,1],[1,0],[1,1,]])

for input_data in test_data:
  (sigmoid_val, logical_val) = AND_obj.predict(input_data)
  print(input_data," = ", logical_val,'\n')


AND_GATE 

[0 0]  =  0 

[0 1]  =  0 

[1 0]  =  0 

[1 1]  =  1 



In [14]:
xdata = np.array([0,0,0,1,1,0,1,1])
tdata = np.array([0,1,1,1])
test = xdata.reshape(4,2)
print(test)
OR_obj = LogicGate("AND_GATE",xdata,tdata)

OR_obj.train()

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Initial error value =  1.630166085478461
step =  0 error value =  1.6274860116851049
step =  400 error value =  1.0503456734303773
step =  800 error value =  0.7701145885621031
step =  1200 error value =  0.6028483980432232
step =  1600 error value =  0.49259520421373715
step =  2000 error value =  0.4148860728466444
step =  2400 error value =  0.3574172241597692
step =  2800 error value =  0.3133419710002928
step =  3200 error value =  0.278557799106687
step =  3600 error value =  0.2504638443366407
step =  4000 error value =  0.2273358431905536
step =  4400 error value =  0.20798818716430467
step =  4800 error value =  0.19158043209851927
step =  5200 error value =  0.17750120180876475
step =  5600 error value =  0.16529574396179034
step =  6000 error value =  0.1546191893430193
step =  6400 error value =  0.14520551139122598
step =  6800 error value =  0.13684638514190806
step =  7200 error value =  0.12937646389723098
step =  7600 error value =  0.12266

In [15]:
xdata = np.array([0,0,0,1,1,0,1,1])
tdata = np.array([1,1,1,0])
test = xdata.reshape(4,2)
print(test)
NAND_obj = LogicGate("AND_GATE",xdata,tdata)

NAND_obj.train()

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Initial error value =  3.2671654161195
step =  0 error value =  3.25940826813725
step =  400 error value =  1.783463368061863
step =  800 error value =  1.26259528477076
step =  1200 error value =  0.9915825370824509
step =  1600 error value =  0.8207649992979464
step =  2000 error value =  0.701274561511313
step =  2400 error value =  0.612265416597152
step =  2800 error value =  0.5431239207624916
step =  3200 error value =  0.48777033874971676
step =  3600 error value =  0.4424252181367603
step =  4000 error value =  0.40459542761566647
step =  4400 error value =  0.3725609588752749
step =  4800 error value =  0.3450928162479216
step =  5200 error value =  0.32128766120734414
step =  5600 error value =  0.3004658250223625
step =  6000 error value =  0.2821057528091475
step =  6400 error value =  0.2658004023124069
step =  6800 error value =  0.25122740091722295
step =  7200 error value =  0.23812811332071537
step =  7600 error value =  0.2262926450709525

In [17]:
input_data = np.array([[0,0],[0,1],[1,0],[1,1]])

s1 = []
s2 = []

new_input_data = []
final_output = []

print (len(input_data))

for index in range(len(input_data)):

  s1 = NAND_obj.predict(input_data[index])
  s2 = OR_obj.predict(input_data[index])
  print("s1 is {}".format(s1))
  print("s2 is {}".format(s2))

  new_input_data.append(s1[-1])
  new_input_data.append(s1[-1])

  (sigmoid_val, logical_val) = AND_obj.predict(np.array(new_input_data))

  final_output.append(logical_val)
  new_input_data = []


for index in range(len(input_data)):
  print(input_data[index], "=", final_output[index],end='')
  print('\n')
  



4
s1 is (array([0.99960637]), 1)
s2 is (array([0.06338463]), 0)
s1 is (array([0.93907592]), 1)
s2 is (array([0.97473529]), 1)
s1 is (array([0.93907727]), 1)
s2 is (array([0.9748408]), 1)
s1 is (array([0.0855561]), 0)
s2 is (array([0.99995473]), 1)
[0 0] = 1

[0 1] = 1

[1 0] = 1

[1 1] = 0

